git config --global alias.st 'status -s'
git config --global alias.aadd 'add .'
git config --global alias.acommit 'commit -am'
git config --global alias.cleanup 'reset @ --hard'
git config --global alias.cleanup '!git reset --hard && git clean -fd'
